# 06 Dec 2013 : PSW : New
# 21 Jan 2014 : PSW : Added permissions; corrected typo in username (doh!)
# 22 Jan 2014 : PSW : Added softdepend, website
# 20 Feb 2014 : PSW : Added unbreakable command
# 23 Feb 2014 : PSW : Split out unbreakable.anvil from .ench
# 28 Mar 2016 : PSW : 4.1 changed default perm on armor/weapons/tools to false
# 07 May 2016 : PSW : Added permission-message for /unbk
# 29 Oct 2016 : PSW : 4.7 Added unbreakable.elytra

name: Unbreakable
main: com.yahoo.phil_work.unbreakable.Unbreakable
version: 4.7
author: filbert66
description: Stops armor and tools from breaking
softdepend: [LanguagesAPI]
# Until Update with new MaterialCategory 
loadbefore: [AntiCreeper, AntiFire]
website: dev.bukkit.org/bukkit-plugins/unbreakableitems

permissions:
  unbreakable.*:
    description: Gives access to ALL unbreakable features
    children:
      unbreakable.armor: true
      unbreakable.tools: true
      unbreakable.weapons: true
      unbreakable.elytra: true
      unbreakable.cmd: true
      unbreakable.ench: true
      unbreakable.anvil: true
  unbreakable.armor:
    description: Allows auto protect this user's armor as unbreakable
    default: false
  unbreakable.weapons:
    description: Allows auto protect user's weapons as unbreakable
    default: false
  unbreakable.tools:
    description: Allows auto protect user's tools as unbreakable
    default: false
  unbreakable.cmd:
    description: Allows enchanting held item with Unbreakable by command
    default: op
  unbreakable.ench:
    description: Allows enchanting item with Unbreakable on Enchant table 
    default: true
  unbreakable.anvil:
    description: Allows enchanting an item with an Unbreakable book on anvil
    default: true
  unbreakable.elytra: 
    description: Allows auto protect only user's elytra as unbreakable
    default: false

commands:
  unbk:
    alias: unbreakable
    description: enchants held item with Unbreakable
    usage: Use when holding repairable item with sufficient XP 
    permission: unbreakable.cmd
    permission-message: You do not have permission to use /<command>>
  
