# Example Config for 
# NOTHING automatically unbreakable, only what players enchant or for specially tagged (by lore) items

Message on making unbreakable: true
Message on enchant cancel: true
Message on enchant: false

Also repair: false

Anvil enchant delay sec: 5
Anvil enchant cost: 8

# Not set, so defaults to ALL
#Enchanting worldlist: 
#- world

Lore unbreakable string: Unbreakable

Protect armor: false
Protect tools: false
Protect weapons: false

# Auto fix worldlist:
# - world

# No permissions check if this turned on
Unbreakable on spawn: false
# Permissions checked for these three
# Set to try to catch LegendaryWeapons drops right away
Unbreakable on pickup: true
# Only effective for tools and weapons, may not catch armor
Unbreakable on hold: false
# Checks entire player inventory
Unbreakable on join: false
# remove Unbreakable when entering world not in 'Auto fix worldlist', if it's been set
Breakable on leave world: false


